"""
geobridge.modules.extract
~~~~~~~~~~~~~~~~~~~~~~~~~

Extract spatial and temporal subsets from Copernicus ARCO Zarr stores
and write them as Cloud Optimized GeoTIFF (COG) files.

The module is designed against the live ECMWF ARCO Data Lake at
``arco.datastores.ecmwf.int`` (verified 2026-05-05).

Two Zarr archive flavours exist for each dataset and the right one is
picked automatically:

- **time_chunked** — chunked along the time axis. Use for spatial maps
  over short periods (the typical GIS use case).
- **geo_chunked** — chunked along the spatial axes. Use for long time
  series at a single point.

Requires the ``[zarr]`` optional dependencies::

    pip install "geobridge[zarr]"
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from functools import lru_cache
from pathlib import Path
from typing import Optional, Union

from geobridge.auth import auth_header, is_authenticated

logger = logging.getLogger(__name__)

DateLike = Union[str, datetime]
PathLike = Union[str, os.PathLike]

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_OVERRIDES_PATH = (
    Path(__file__).parent.parent / "semantic" / "arco_overrides.yaml"
)
_ARCO_SNAPSHOT_PATH = (
    Path(__file__).parent.parent / "semantic" / "arco_snapshot.yaml"
)
_CDS_SNAPSHOT_PATH = (
    Path(__file__).parent.parent / "semantic" / "cds_snapshot.yaml"
)

# Aggregations supported. Maps user-friendly name → (pandas resample freq, op).
_AGGREGATIONS: dict[str, Optional[tuple[str, str]]] = {
    "raw": None,                      # No aggregation — write all timesteps
    "daily_mean": ("D", "mean"),
    "daily_max": ("D", "max"),
    "daily_min": ("D", "min"),
    "monthly_mean": ("MS", "mean"),
    "monthly_max": ("MS", "max"),
    "monthly_min": ("MS", "min"),
    "annual_mean": ("YS", "mean"),
    "annual_max": ("YS", "max"),
}

# Heuristic for picking time_chunked vs geo_chunked.  When the user asks for
# more than this many days at a single point, the geo_chunked store is faster.
_GEO_CHUNK_THRESHOLD_DAYS = 90


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class ExtractionError(RuntimeError):
    """Raised when Zarr extraction or GeoTIFF writing fails."""


# ---------------------------------------------------------------------------
# Lazy imports for optional heavy dependencies
# ---------------------------------------------------------------------------

def _require_xarray():
    """Import xarray and rioxarray on demand."""
    try:
        import xarray as xr
        import rioxarray  # noqa: F401  (registers the .rio accessor)
        import numpy as np
        return xr, np
    except ImportError as exc:
        raise ExtractionError(
            "zarr_to_geotiff() requires the [zarr] extras. Install with:\n"
            "    pip install 'geobridge[zarr]'"
        ) from exc


# ---------------------------------------------------------------------------
# Catalogue loading
# ---------------------------------------------------------------------------

@lru_cache(maxsize=1)
def _load_arco_snapshot() -> dict:
    """Load and cache the ARCO catalogue snapshot.

    The snapshot is generated by ``scripts/refresh_arco_catalogue.py`` and
    contains, for every ARCO-available dataset, the Zarr URLs, variable
    list with units and value ranges, dimensions, and optional WMTS
    endpoint — all sourced directly from ECMWF's own STAC catalogue at
    ``arco.datastores.ecmwf.int``.

    Returns an empty dict when the snapshot file is missing.  Extraction
    still works for any dataset present in ``arco_overrides.yaml``.
    """
    try:
        import yaml
    except ImportError as exc:
        raise ExtractionError(
            "PyYAML is required. Install with: pip install pyyaml"
        ) from exc

    if not _ARCO_SNAPSHOT_PATH.exists():
        logger.warning(
            "ARCO catalogue snapshot not found at %s. "
            "Run scripts/refresh_arco_catalogue.py to generate it. "
            "Extraction will still work for datasets in arco_overrides.yaml.",
            _ARCO_SNAPSHOT_PATH,
        )
        return {}
    with _ARCO_SNAPSHOT_PATH.open(encoding="utf-8") as fp:
        data = yaml.safe_load(fp) or {}
    return data.get("datasets", {}) or {}


@lru_cache(maxsize=1)
def _load_overrides() -> dict:
    """Load and cache the slim ARCO overrides file.

    The overrides file holds only the CDS-to-ARCO variable name alias
    mapping (CDS long form like ``2m_temperature`` to ARCO short form
    like ``t2m``).  Since v0.2 everything else is auto-derived from the
    ARCO STAC catalogue snapshot.
    """
    try:
        import yaml
    except ImportError as exc:
        raise ExtractionError(
            "PyYAML is required. Install with: pip install pyyaml"
        ) from exc

    if not _OVERRIDES_PATH.exists():
        logger.warning(
            "Variable alias overrides not found at %s", _OVERRIDES_PATH,
        )
        return {}
    with _OVERRIDES_PATH.open(encoding="utf-8") as fp:
        data = yaml.safe_load(fp) or {}
    return data.get("overrides", {}) or {}


@lru_cache(maxsize=1)
def _load_cds_snapshot() -> dict:
    """Load and cache the CDS catalogue snapshot (auxiliary, optional)."""
    try:
        import yaml
    except ImportError:
        return {}
    if not _CDS_SNAPSHOT_PATH.exists():
        return {}
    with _CDS_SNAPSHOT_PATH.open(encoding="utf-8") as fp:
        data = yaml.safe_load(fp) or {}
    return data.get("datasets", {}) or {}


def _pick_default_subset(dataset_entry: dict) -> Optional[str]:
    """Pick a sensible default subset id for a dataset.

    Preference: a subset whose id is in {sfc, all, surface} (typical primary
    subset names in the ARCO catalogue), else the first one in alphabetical
    order so behaviour is deterministic.
    """
    subsets = dataset_entry.get("subsets", {}) or {}
    if not subsets:
        return None
    for preferred in ("sfc", "all", "surface"):
        if preferred in subsets:
            return preferred
    return sorted(subsets)[0]


def _normalise_zarr_keys(zarr_block: dict) -> dict:
    """Convert ARCO snapshot camelCase keys to the extract module's snake_case.

    ECMWF's STAC uses ``timeChunked`` / ``geoChunked`` / ``downsampled4``.
    The rest of extract.py reads ``time_chunked`` / ``geo_chunked``.
    Translation happens here once.
    """
    out: dict[str, str] = {}
    for key, url in (zarr_block or {}).items():
        if not url:
            continue
        if key == "timeChunked":
            out["time_chunked"] = url
        elif key == "geoChunked":
            out["geo_chunked"] = url
        elif key.startswith("downsampled"):
            # Keep downsampled variants under the same key for now
            out[key] = url
        else:
            out[key] = url
    return out


def _get_dataset_entry(dataset_id: str, subset: Optional[str] = None) -> dict:
    """Look up access details for *dataset_id*, with helpful errors on miss.

    Builds the entry dict the rest of extract.py expects.  Primary source
    is the auto-generated ARCO snapshot (``arco_snapshot.yaml``);
    variable aliases come from the small ``arco_overrides.yaml``.  CDS
    snapshot metadata is attached under ``_cds`` for informational use.

    Parameters
    ----------
    dataset_id : str
        ARCO catalogue id, e.g. ``reanalysis_era5_single_levels``.
        Hyphens in CDS-style ids (``reanalysis-era5-single-levels``)
        are converted to underscores transparently.
    subset : str, optional
        Subset within the dataset (e.g. ``sfc`` for ERA5 single levels).
        Defaults to a sensible primary subset.
    """
    # CDS-style ids use hyphens; ARCO uses underscores. Accept either.
    canonical_id = dataset_id.replace("-", "_")
    arco = _load_arco_snapshot()
    overrides = _load_overrides()

    if canonical_id not in arco:
        # Fall back to slim overrides keyed by the CDS-style id
        if dataset_id in overrides and "zarr" in overrides[dataset_id]:
            return dict(overrides[dataset_id])
        available = sorted(arco.keys())
        raise ExtractionError(
            f"Dataset {dataset_id!r} not in the ARCO catalogue snapshot.\n"
            f"Datasets currently available for extraction: {available[:10]}"
            f"{' ...' if len(available) > 10 else ''}\n\n"
            "To refresh the snapshot:\n"
            "    python scripts/refresh_arco_catalogue.py\n\n"
            "If the dataset is genuinely not in ARCO, it can only be "
            "accessed via the legacy CDS download API (cdsapi)."
        )

    dataset_entry = arco[canonical_id]
    subsets = dataset_entry.get("subsets", {}) or {}
    chosen = subset or _pick_default_subset(dataset_entry)
    if chosen is None or chosen not in subsets:
        available_subsets = sorted(subsets)
        raise ExtractionError(
            f"Dataset {dataset_id!r} has no subset {chosen!r}.\n"
            f"Available subsets: {available_subsets}"
        )

    subset_entry = subsets[chosen]

    # Build the entry shape the rest of extract.py expects
    entry: dict[str, Any] = {
        "dataset_id": canonical_id,
        "subset_id": chosen,
        "service": dataset_entry.get("service", "C3S"),
        "title": dataset_entry.get("title", canonical_id),
        "zarr": _normalise_zarr_keys(subset_entry.get("zarr", {})),
        "wmts_url": subset_entry.get("wmts") or "",
        "bbox": subset_entry.get("bbox"),
        "time_start": subset_entry.get("time_start"),
        "time_end": subset_entry.get("time_end"),
        "dimensions": subset_entry.get("dimensions", {}),
        "variables_meta": subset_entry.get("variables", {}),
    }

    # Derive native resolution from the latitude step if available
    lat_dim = subset_entry.get("dimensions", {}).get("latitude") or {}
    if "step" in lat_dim:
        entry["native_resolution_deg"] = float(lat_dim["step"])

    # Derive latitude direction from the extent
    lat_extent = lat_dim.get("extent")
    if lat_extent and len(lat_extent) == 2 and lat_extent[0] is not None:
        entry["coordinate_order"] = (
            "lat_ascending" if lat_extent[0] < lat_extent[1] else "lat_descending"
        )

    # Derive longitude convention from the extent
    lon_dim = subset_entry.get("dimensions", {}).get("longitude") or {}
    lon_extent = lon_dim.get("extent")
    if lon_extent and len(lon_extent) == 2 and lon_extent[0] is not None:
        entry["longitude_convention"] = (
            "minus180_to_180" if lon_extent[0] < 0 else "zero_to_360"
        )

    # Variable aliases come from the slim overrides file (CDS long to ARCO short)
    aliases_top = overrides.get("variable_aliases", {}) or {}
    aliases_per_dataset = (overrides.get(canonical_id) or {}).get(
        "variable_aliases", {}
    )
    entry["variable_aliases"] = {**aliases_top, **aliases_per_dataset}

    # Attach CDS STAC metadata if it happens to be available
    cds = _load_cds_snapshot()
    # CDS catalogue uses hyphenated ids
    cds_id = dataset_id.replace("_", "-")
    if cds_id in cds:
        entry["_cds"] = cds[cds_id]

    return entry


def _resolve_variable_name(entry: dict, variable: str) -> str:
    """Translate a CDS-style variable name to the ARCO short name."""
    aliases = entry.get("variable_aliases", {})
    # If it is already a short name (i.e. value of an alias), leave it
    if variable in aliases.values():
        return variable
    # Translate from the long form
    if variable in aliases:
        return aliases[variable]
    # Unknown — let xarray raise a clear KeyError later
    return variable


# ---------------------------------------------------------------------------
# Zarr opening
# ---------------------------------------------------------------------------

def _pick_chunking(entry: dict, time_range: tuple, bbox: tuple) -> str:
    """Choose time_chunked vs geo_chunked based on the request shape."""
    # If only one is available, no choice.
    zarr_urls = entry.get("zarr", {})
    if "time_chunked" in zarr_urls and "geo_chunked" not in zarr_urls:
        return "time_chunked"
    if "geo_chunked" in zarr_urls and "time_chunked" not in zarr_urls:
        return "geo_chunked"

    # Compute approximate request shape
    t_start, t_end = time_range
    if isinstance(t_start, str):
        t_start = datetime.fromisoformat(t_start.replace("Z", "+00:00")
                                         if "T" in t_start else t_start)
    if isinstance(t_end, str):
        t_end = datetime.fromisoformat(t_end.replace("Z", "+00:00")
                                       if "T" in t_end else t_end)
    n_days = max((t_end - t_start).days, 1)

    west, south, east, north = bbox
    bbox_area_deg2 = max((east - west) * (north - south), 0.0001)

    # Heuristic: tiny bbox + long time → geo_chunked; otherwise time_chunked
    if bbox_area_deg2 < 1.0 and n_days > _GEO_CHUNK_THRESHOLD_DAYS:
        return "geo_chunked"
    return "time_chunked"


def _open_arco_zarr(zarr_url: str):
    """Open an ARCO Zarr store with bearer-token auth."""
    xr, _ = _require_xarray()

    if not is_authenticated():
        raise ExtractionError(
            "Not authenticated. Call geobridge.authenticate() before "
            "calling zarr_to_geotiff()."
        )

    storage_options = {"headers": auth_header()}
    logger.debug("Opening ARCO Zarr store at %s", zarr_url)
    try:
        return xr.open_zarr(
            zarr_url,
            consolidated=True,
            storage_options=storage_options,
            chunks="auto",
        )
    except Exception as exc:
        raise ExtractionError(
            f"Failed to open ARCO Zarr store {zarr_url}: {exc}\n\n"
            "Common causes:\n"
            "  - Your CDS API key is invalid or expired\n"
            "  - You haven't accepted the dataset licence on the CDS portal\n"
            "  - The ARCO service is rate-limiting you (try again later)\n"
            "  - The Zarr URL has changed (check arco_overrides.yaml)"
        ) from exc


# ---------------------------------------------------------------------------
# Subsetting
# ---------------------------------------------------------------------------

def _coord_name(da, candidates: tuple[str, ...]) -> Optional[str]:
    """Return the first coordinate name from *candidates* present on *da*."""
    return next((c for c in candidates if c in da.coords), None)


def _select_subset(ds, variable: str, bbox: tuple, time_range: tuple,
                   entry: dict):
    """Apply spatial and temporal subsetting to an xarray Dataset.

    Returns
    -------
    da : xarray.DataArray
        The subsetted variable.
    coord_names : dict
        Names of the coordinate axes in the returned DataArray
        (``lon``, ``lat``, ``time``).
    """
    # Look up the variable in the dataset
    if variable not in ds.data_vars:
        available = list(ds.data_vars)[:20]
        raise ExtractionError(
            f"Variable {variable!r} not in Zarr store. "
            f"First 20 available variables: {available}"
        )
    da = ds[variable]

    # Coordinate names vary by dataset
    lon_name = _coord_name(da, ("longitude", "lon", "x"))
    lat_name = _coord_name(da, ("latitude", "lat", "y"))
    time_name = _coord_name(da, ("time", "valid_time", "t"))
    if lon_name is None or lat_name is None:
        raise ExtractionError(
            "Could not find longitude/latitude coordinates. "
            f"Available coords: {list(da.coords)}"
        )

    west, south, east, north = bbox

    # Handle 0–360 longitude convention if the dataset uses it
    if entry.get("longitude_convention") == "zero_to_360":
        if west < 0:
            west += 360
        if east < 0:
            east += 360
        if west > east:
            west, east = east, west

    # Latitude direction depends on the dataset
    lat_values = da[lat_name].values
    lat_ascending = bool(lat_values[0] < lat_values[-1])
    lat_slice = slice(south, north) if lat_ascending else slice(north, south)

    da = da.sel({lon_name: slice(west, east), lat_name: lat_slice})

    if time_name is not None:
        t_start, t_end = time_range
        da = da.sel({time_name: slice(t_start, t_end)})

    if 0 in da.sizes.values():
        raise ExtractionError(
            f"Subsetting returned an empty array for variable {variable!r}.\n"
            f"  bbox = {bbox}\n"
            f"  time_range = {time_range}\n"
            f"  resulting shape = {dict(da.sizes)}\n\n"
            "Likely causes:\n"
            "  - bbox too small to contain any grid cells "
            f"(grid is ~{entry.get('native_resolution_deg', '?')}° spaced)\n"
            "  - time_range outside dataset coverage "
            f"({entry.get('time_range', {})})"
        )

    return da, {"lon": lon_name, "lat": lat_name, "time": time_name}


def _aggregate(da, aggregation: str, time_name: Optional[str]):
    """Apply temporal aggregation if requested."""
    if aggregation == "raw" or time_name is None:
        return da
    if aggregation not in _AGGREGATIONS:
        raise ExtractionError(
            f"Unknown aggregation {aggregation!r}. "
            f"Valid options: {list(_AGGREGATIONS)}"
        )
    spec = _AGGREGATIONS[aggregation]
    if spec is None:
        return da
    freq, op = spec
    return getattr(da.resample({time_name: freq}), op)()


def _ensure_crs(da, lon_name: str, lat_name: str):
    """Rename to standard x/y dims and attach a CRS for rioxarray export.

    Also ensures the y-axis is descending (north-up) which prevents
    the 'NotGeoreferencedWarning' from rasterio when the affine
    transform appears to be identity.
    """
    rename_map = {}
    if lon_name != "x":
        rename_map[lon_name] = "x"
    if lat_name != "y":
        rename_map[lat_name] = "y"
    if rename_map:
        da = da.rename(rename_map)

    # Ensure y-axis is descending (north at top) — rioxarray needs this
    # to compute a valid geotransform
    y_vals = da.coords["y"].values
    if len(y_vals) > 1 and y_vals[0] < y_vals[-1]:
        da = da.sortby("y", ascending=False)

    da = da.rio.set_spatial_dims(x_dim="x", y_dim="y", inplace=False)
    if da.rio.crs is None:
        da = da.rio.write_crs("EPSG:4326")

    # Force rioxarray to recompute the transform from the coordinate arrays
    # This prevents the identity-transform warning
    da.encoding.pop("transform", None)

    return da


def _write_geotiff(da, output_path: Path, cog: bool) -> Path:
    """Write a DataArray to GeoTIFF (optionally Cloud Optimized)."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if cog:
        da.rio.to_raster(
            output_path, driver="COG",
            compress="DEFLATE", BLOCKSIZE=512,
        )
    else:
        da.rio.to_raster(
            output_path, driver="GTiff",
            compress="DEFLATE", tiled=True,
        )
    return output_path


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def list_datasets() -> list[str]:
    """Return the IDs of all datasets supported for extraction.

    "Supported" means the dataset is present in the ARCO catalogue
    snapshot (which is auto-generated from ECMWF's STAC catalogue at
    arco.datastores.ecmwf.int).  All 27 datasets in the ARCO data lake
    are wired up automatically — no per-dataset code changes needed.

    Examples
    --------
    >>> import geobridge as gb
    >>> for dsid in gb.list_datasets():
    ...     print(dsid)
    """
    snapshot = _load_arco_snapshot()
    if snapshot:
        return sorted(snapshot.keys())
    # Fallback if the snapshot file is missing
    return sorted(_load_overrides().keys())


def list_variables(dataset_id: str, subset: Optional[str] = None) -> list[str]:
    """Return the variable short names available for a dataset.

    Reads the variable list directly from the ARCO catalogue snapshot.
    Variable names are returned in their ARCO short form (e.g. ``t2m``,
    ``pm2p5``, ``utci``) — the form actually used inside the Zarr store.
    Either short or long names can be passed to :func:`zarr_to_geotiff`.

    Parameters
    ----------
    dataset_id : str
        ARCO catalogue id, e.g. ``reanalysis_era5_single_levels``.
    subset : str, optional
        Specific subset (e.g. ``sfc``).  Defaults to the primary subset.

    Examples
    --------
    >>> gb.list_variables("reanalysis_era5_single_levels")
    ['blh', 'cbh', 'd2m', ..., 't2m', 'tp', ...]
    """
    entry = _get_dataset_entry(dataset_id, subset=subset)
    # Prefer the actual variable list captured from the ARCO snapshot
    var_meta = entry.get("variables_meta") or {}
    if var_meta:
        return sorted(var_meta.keys())
    # Fall back to alias keys
    return list(entry.get("variable_aliases", {}).keys())


def zarr_to_geotiff(
    dataset: str,
    variable: str,
    bbox: tuple[float, float, float, float],
    time_range: tuple[DateLike, DateLike],
    aggregation: str = "raw",
    output_path: Optional[PathLike] = None,
    cog: bool = True,
    target_crs: Optional[str] = None,
    chunking: Optional[str] = None,
) -> Path:
    """Extract a subset of an ARCO Zarr store as a GeoTIFF.

    Parameters
    ----------
    dataset : str
        Dataset identifier, e.g. ``'reanalysis-era5-single-levels'``.
        Must be present in the GeoBridge ARCO catalogue.
    variable : str
        Variable name in either CDS long form (``'2m_temperature'``) or
        ARCO short form (``'t2m'``).
    bbox : tuple
        Spatial extent as ``(west, south, east, north)`` in WGS-84 degrees.
    time_range : tuple
        ``(start, end)`` — either ISO-8601 date strings or datetime objects.
    aggregation : str
        Temporal aggregation to apply before writing.  One of:
        ``'raw'``, ``'daily_mean'``, ``'daily_max'``, ``'daily_min'``,
        ``'monthly_mean'``, ``'monthly_max'``, ``'monthly_min'``,
        ``'annual_mean'``, ``'annual_max'``.
    output_path : path-like, optional
        Destination file. Defaults to
        ``./{dataset}_{variable}_{aggregation}.tif`` in the current directory.
    cog : bool
        If True (default) write a Cloud Optimized GeoTIFF.
    target_crs : str, optional
        Reproject to this CRS, e.g. ``'EPSG:3857'``.
        Default keeps the native EPSG:4326.
    chunking : {'time_chunked', 'geo_chunked'}, optional
        Force a specific chunking flavour.  Default is to auto-pick based
        on the request shape.

    Returns
    -------
    Path
        Path to the written GeoTIFF.

    Raises
    ------
    ExtractionError
        If the dataset, variable, authentication, or write step fails.

    Examples
    --------
    >>> import geobridge as gb
    >>> gb.authenticate()
    >>> tif = gb.zarr_to_geotiff(
    ...     dataset="reanalysis-era5-single-levels",
    ...     variable="2m_temperature",
    ...     bbox=(23.0, 37.5, 24.5, 38.5),
    ...     time_range=("2023-07-01", "2023-07-31"),
    ...     aggregation="monthly_mean",
    ...     cog=True,
    ... )
    >>> print(tif)
    """
    xr, _ = _require_xarray()

    # 1. Catalogue lookup
    entry = _get_dataset_entry(dataset)
    short_var = _resolve_variable_name(entry, variable)

    # 2. Pick chunking flavour and Zarr URL
    flavour = chunking or _pick_chunking(entry, time_range, bbox)
    zarr_urls = entry.get("zarr", {})
    if flavour not in zarr_urls:
        raise ExtractionError(
            f"Chunking flavour {flavour!r} not available for dataset "
            f"{dataset!r}.  Available: {list(zarr_urls)}"
        )
    zarr_url = zarr_urls[flavour]
    logger.info("Using %s archive for %s", flavour, dataset)

    # 3. Open the store
    ds = _open_arco_zarr(zarr_url)

    # 4. Subset
    da, coord_names = _select_subset(ds, short_var, bbox, time_range, entry)

    # 5. Aggregate
    da = _aggregate(da, aggregation, coord_names["time"])

    # 6. Attach CRS
    da = _ensure_crs(da, coord_names["lon"], coord_names["lat"])

    # 7. Optional reprojection
    if target_crs and target_crs.upper() != "EPSG:4326":
        try:
            da = da.rio.reproject(target_crs)
        except Exception as exc:
            raise ExtractionError(
                f"Reprojection to {target_crs} failed: {exc}"
            ) from exc

    # 8. Write
    if output_path is None:
        safe_dataset = dataset.replace("/", "_")
        output_path = (Path.cwd() /
                       f"{safe_dataset}_{short_var}_{aggregation}.tif")
    output_path = Path(output_path)

    try:
        return _write_geotiff(da, output_path, cog)
    except Exception as exc:
        raise ExtractionError(
            f"Failed to write GeoTIFF to {output_path}: {exc}"
        ) from exc
